// Generated by npm run design:generate.
package com.example.newsworthy;

final class LevelPalette {
    private LevelPalette() {}
    static int background(int score) {
        switch (score) {
            case 1: return R.drawable.widget_level_1;
            case 2: return R.drawable.widget_level_2;
            case 3: return R.drawable.widget_level_3;
            case 4: return R.drawable.widget_level_4;
            case 5: return R.drawable.widget_level_5;
            case 6: return R.drawable.widget_level_6;
            case 7: return R.drawable.widget_level_7;
            case 8: return R.drawable.widget_level_8;
            case 9: return R.drawable.widget_level_9;
            case 10: return R.drawable.widget_level_10;
            default: return R.drawable.widget_background;
        }
    }
}
