// Generated by npm run design:assets. Static imports are required by Metro.
export const gradientImages = [
  { light: require('../assets/gradients/1-light.png'), dark: require('../assets/gradients/1-dark.png') },
  { light: require('../assets/gradients/2-light.png'), dark: require('../assets/gradients/2-dark.png') },
  { light: require('../assets/gradients/3-light.png'), dark: require('../assets/gradients/3-dark.png') },
  { light: require('../assets/gradients/4-light.png'), dark: require('../assets/gradients/4-dark.png') },
  { light: require('../assets/gradients/5-light.png'), dark: require('../assets/gradients/5-dark.png') },
  { light: require('../assets/gradients/6-light.png'), dark: require('../assets/gradients/6-dark.png') },
  { light: require('../assets/gradients/7-light.png'), dark: require('../assets/gradients/7-dark.png') },
  { light: require('../assets/gradients/8-light.png'), dark: require('../assets/gradients/8-dark.png') },
  { light: require('../assets/gradients/9-light.png'), dark: require('../assets/gradients/9-dark.png') },
  { light: require('../assets/gradients/10-light.png'), dark: require('../assets/gradients/10-dark.png') },
];
