import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { channels, resolveTheme } from '../design/colors.js';
import { cssName } from '../design/names.js';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const readJson = async path => JSON.parse(await readFile(resolve(root, path), 'utf8'));
// Colour (palette.json), every other token (tokens.json) and the cross-surface
// contract (surfaces.json) are edited separately and shipped as one module.
const palette = await readJson('design/palette.json');
const scale = await readJson('design/tokens.json');
const surfaces = await readJson('design/surfaces.json');
const source = { ...palette, ...scale };
const check = process.argv.includes('--check');
const files = new Map();
const output = (path, content) => files.set(path, content);
const json = data => JSON.stringify(data, null, 2) + '\n';
const resolved = entry => ({ ...entry, light: resolveTheme(entry, source.appearance.light), dark: resolveTheme(entry, source.appearance.dark, true) });
const tokens = { ...source, surfaces, brand: resolved(source.brand), levels: source.levels.map(resolved) };
output('public/tokens.js', '// Generated by npm run design:generate. Edit design/palette.json, design/tokens.json or design/surfaces.json.\nexport default ' + JSON.stringify(tokens, null, 2) + ';\n');
// Every web token is `--<group>-<key>`, kebab-cased; a half step's point
// becomes `_`. The admin page's own system carries an `admin-` prefix.
const rem = value => `${+(value / 16).toFixed(4)}rem`;
const px = value => `${value}px`;
const CSS_UNITS = { type: rem, text: rem, weight: String, leading: String, tracking: v => `${v}em`, space: rem, radius: px, stroke: px,
  dash: String, opacity: String, motion: v => `${v}ms`, layer: String, measure: v => typeof v === 'number' ? rem(v) : v };
const shadowRgb = channels(palette.control.shadow).join(', ');
const cssVars = (system, prefix = '') => [
  ...Object.entries(system.font).map(([key, value]) => `--${prefix}font-${key}: ${value};`),
  ...Object.entries(CSS_UNITS).filter(([group]) => group in system).flatMap(([group, unit]) => Object.entries(system[group])
    .sort(([a], [b]) => isNaN(a) || isNaN(b) ? 0 : a - b).map(([key, value]) => `--${cssName(prefix + group, key)}: ${unit(value)};`)),
  ...Object.entries(system.shadow ?? {}).filter(([, shadow]) => 'offsetY' in shadow && 'opacity' in shadow && !('elevation' in shadow))
    .map(([key, shadow]) => `--${cssName(prefix + 'shadow', key)}: 0 ${shadow.offsetY}px ${shadow.radius}px rgba(${shadowRgb}, ${shadow.opacity});`),
];
const scaleVars = cssVars(scale);
// The admin page is web-only and internal, so it has its own scale; colour
// stays shared, because its chart is drawn in the reading palette.
const admin = await readJson('design/admin.json');
output('public/admin-tokens.css', '/* Generated by npm run design:generate. Edit design/admin.json. */\n:root {\n' + cssVars(admin, 'admin-').map(line => `  ${line}`).join('\n') + '\n}\n');
const paletteVars = entry => `--level-color: ${channels(entry.primary).join(', ')}; --level-companion: ${channels(entry.companion).join(', ')};\n  ` + ['light', 'dark'].map(mode => ['accent', 'tinted', 'elevated', 'start', 'center', 'end'].map(key => `--level-${key}-${mode}: ${entry[mode][key]};`).join(' ')).join('\n  ');
const themeVars = (mode, selector = ':root') => {
  const a = source.appearance[mode];
  return `${selector} {\n  --surface: ${a.surface}; --ink: ${a.ink}; --ink-muted: ${a.muted}; --ink-faint: ${a.faint}; --rule: ${a.rule}; --danger: ${a.danger}; --ink-on-gradient-muted: ${a.gradientMuted};\n  --accent: var(--level-accent-${mode}); --surface-tinted: var(--level-tinted-${mode}); --surface-2: var(--level-elevated-${mode});\n  --gradient-start: var(--level-start-${mode}); --gradient-center: var(--level-center-${mode}); --gradient-end: var(--level-end-${mode});\n  --wash: ${a.wash}; --glow: ${a.glow}; --veil: ${a.veil};\n}\n`;
};
// Appearance-dependent aliases must be declared on level-bearing components
// too: inherited custom-property aliases resolve at their defining element.
const aliasScope = ':root, [data-level], [data-brand]';
output('public/tokens.css', '/* Generated by npm run design:generate. */\n:root {\n  color-scheme: light dark;\n  ' + paletteVars(tokens.brand) + '\n' + scaleVars.map(line => `  ${line}`).join('\n') + '\n}\n' + tokens.levels.map(entry => `[data-level="${entry.score}"] { ${paletteVars(entry)} }`).join('\n') + '\n' + themeVars('light', aliasScope) + '@media (prefers-color-scheme: dark) {\n' + themeVars('dark', aliasScope) + '}\n' + themeVars('light', '[data-appearance="light"], [data-appearance="light"] [data-level]') + themeVars('dark', '[data-appearance="dark"], [data-appearance="dark"] [data-level]'));
const android = 'apps/client/plugins/widget-android/res';
for (const mode of ['light', 'dark']) {
  const colors = new Map();
  const add = (name, value) => colors.set('nw_' + name, value);
  add('identity_surface', tokens.identity[mode].surface);
  add('identity_ink', tokens.identity[mode].ink);
  add('gradient_muted', source.appearance[mode].gradientMuted);
  for (const key of ['surface', 'ink', 'muted', 'faint', 'rule', 'danger']) add(key, source.appearance[mode][key]);
  for (const key of ['accent', 'tinted', 'elevated', 'start', 'center', 'end']) add('brand_' + key, tokens.brand[mode][key]);
  for (const entry of tokens.levels) for (const key of ['start', 'center', 'end', 'accent']) add(`level_${entry.score}_${key}`, entry[mode][key]);
  output(`${android}/values${mode === 'dark' ? '-night' : ''}/newsworthy_palette.xml`, '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by npm run design:generate. -->\n<resources>\n' + [...colors].map(([name, value]) => `  <color name="${name}">${value}</color>`).join('\n') + '\n</resources>\n');
}
const drawable = name => `<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by npm run design:generate. -->\n<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">\n  <gradient android:angle="315" android:startColor="@color/nw_${name}_start" android:centerColor="@color/nw_${name}_center" android:endColor="@color/nw_${name}_end"/>\n  <corners android:radius="${source.radius.widget}dp"/>\n</shape>\n`;
for (const entry of tokens.levels) output(`${android}/drawable/widget_level_${entry.score}.xml`, drawable(`level_${entry.score}`));
output(`${android}/drawable/widget_background.xml`, drawable('brand'));
output('apps/client/plugins/widget-android/LevelPalette.java', '// Generated by npm run design:generate.\npackage com.example.newsworthy;\n\nfinal class LevelPalette {\n    private LevelPalette() {}\n    static int background(int score) {\n        switch (score) {\n' + tokens.levels.map(entry => `            case ${entry.score}: return R.drawable.widget_level_${entry.score};`).join('\n') + '\n            default: return R.drawable.widget_background;\n        }\n    }\n}\n');
const catalog = 'apps/client/targets/widget/Assets.xcassets';
output(`${catalog}/Contents.json`, json({ info: { version: 1, author: 'newsworthy' } }));
output('apps/client/assets/design.json', json({ identity: tokens.identity, brand: tokens.brand }));
const assetColor = (hex, dark) => ({ idiom: 'universal', ...(dark ? { appearances: [{ appearance: 'luminosity', value: 'dark' }] } : {}), color: { 'color-space': 'srgb', components: Object.fromEntries(['red', 'green', 'blue'].map((c, i) => [c, (channels(hex)[i] / 255).toFixed(6)]).concat([['alpha', '1.000000']])) } });
const colorSet = (name, light, dark) => output(`${catalog}/${name}.colorset/Contents.json`, json({ colors: [assetColor(light), assetColor(dark, true)], info: { version: 1, author: 'newsworthy' } }));
for (const key of ['surface', 'ink', 'muted', 'faint', 'rule', 'danger', 'gradientMuted']) colorSet('Newsworthy' + key[0].toUpperCase() + key.slice(1), source.appearance.light[key], source.appearance.dark[key]);
for (const key of ['accent', 'tinted', 'start', 'center', 'end']) colorSet('Brand' + key[0].toUpperCase() + key.slice(1), tokens.brand.light[key], tokens.brand.dark[key]);
colorSet('AccentColor', tokens.brand.light.accent, tokens.brand.dark.accent);
colorSet('SplashScreenBackground', tokens.brand.light.tinted, tokens.brand.dark.tinted);
for (const entry of tokens.levels) for (const key of ['start', 'center', 'end', 'accent']) colorSet(`Level${String(entry.score).padStart(2, '0')}${key[0].toUpperCase() + key.slice(1)}`, entry.light[key], entry.dark[key]);
let stale = false;
for (const [path, content] of files) {
  const absolute = resolve(root, path);
  if (check) {
    if (await readFile(absolute, 'utf8').catch(() => '') !== content) { console.error('Out of date: ' + path); stale = true; }
  } else {
    await mkdir(dirname(absolute), { recursive: true });
    await writeFile(absolute, content);
  }
}
if (stale) process.exitCode = 1;
else console.log(`${check ? 'Checked' : 'Generated'} ${files.size} shared web and native palette files.`);
